apiVersion: v1
kind: Service
metadata:
    name: olufemioyekanmilinetenlineten
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP 
    selector:
        app: olufemioyekanmilinetenlineten