apiVersion: v1
kind: Service
metadata:
    name: olufemioyekanmilinetenlineten
spec:
    type: LoadBalancer
    ports:
    - port: 81
      targetPort: 81
      protocol: TCP 
    selector:
        app: olufemioyekanmilinetenlineten