apiVersion: v1
kind: Service
metadata:
    name: olufemioyekanmilinetenlineten
spec:
    type: LoadBalancer
    ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP 
    selector:
        app: olufemioyekanmilinetenlineten